### ISSUE TITLE
Import in NodeJS

### ISSUE THREAD

**Issue by fetherolfjd** [gchudnov/inkjet#3]
Hi, I we're running NodeJS 6.9.4 and I was under the impression that ```import``` still wasn't supported natively in Node? With that in mind, doesn't the migration of Inkjet to ES6 with the release of 2.1.0 and ```import``` statements essentially break compatibility with NodeJS?

**Comment by gchudnov** [comment]
hm.. indeed, it looks I broke it :(, let me fix it..

**Comment by fetherolfjd** [comment]
Sorry to be the bearer of bad news; just really caught me off-guard when stuff started breaking. Thanks for all the work you do with Inkjet.

**Comment by gchudnov** [comment]
Just published 2.1.2, should work now.
Sorry for the broken build :disappointed: 

Please, let me know if it works.
Thank you!

**Comment by gchudnov** [comment]
Actually I thought no-one uses it... :)
Are you using it for node.js or the browser?

I'm not particular happy with the number of jpeg-formats inkjet supports now (e.g. no progressive JPEG). To improve it, I compiled libjpeg to javascript some time ago.
It was promising, but the resulting library is huge (~1Mb) comparing to (~200Kb) that we have now.

**Comment by fetherolfjd** [comment]
That seems to work fine now, thanks.

We're using it for node.js doing some light server side processing; mainly just getting the metadata and exif data at the moment.
